apiVersion: v1
kind: Service
metadata:
  name: django-main-service
spec:
  type: ClusterIP
  selector:
    app: django-messaging
    version: blue  # Default to blue
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000